flag_management:
  individual_flags:
    - name: smart-tests
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "project"
        - type: "patch"

cli:
  plugins:
    pycoverage:
      report_type: "json"
ignore:
  - "tool_integration_service/test/test_api.py"
  - "tool_integration_service/exception/exception.py"